In [1]:
import numpy as np

In [2]:
# Creating 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

In [3]:
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

In [4]:
# Addition
result_addition = array1 + array2

In [6]:
result_addition

array([[ 8, 10, 12],
       [14, 16, 18]])

In [7]:
# Subtraction
result_subtraction = array1 - array2
result_subtraction

array([[-6, -6, -6],
       [-6, -6, -6]])

In [8]:
# Multiplication
result_multiplication = array1 * array2
result_multiplication

array([[ 7, 16, 27],
       [40, 55, 72]])

In [9]:
# Division
result_division = array1 / array2
result_division

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [10]:
# Exponentiation
result_exponentiation = array1 ** 2
result_exponentiation

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
# Modulus
result_modulus = array1 % 2
result_modulus

array([[1, 0, 1],
       [0, 1, 0]])

In [12]:
# Floor Division
result_floor_division = array1 // 2
result_floor_division

array([[0, 1, 1],
       [2, 2, 3]])

In [13]:
# Matrix Multiplication (Dot Product)
result_dot_product = np.dot(array1, array2.T)  # Transpose of array2 to match dimensions
result_dot_product

array([[ 50,  68],
       [122, 167]])