In [2]:
import numpy as np

In [3]:
# Creating a 2D array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

In [4]:
# Add a scalar to each element using +=
array += 2

In [5]:
array

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
# Subtract a scalar from each element using -=
array -= 1
array

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
# Perform bitwise AND with a scalar using &=
array &= 2

In [9]:
array

array([[2, 2, 0],
       [0, 2, 2]])

In [10]:
# Perform bitwise OR with a scalar using |=
array |= 4
array

array([[6, 6, 4],
       [4, 6, 6]])

In [11]:
# Perform bitwise XOR with a scalar using ^=
array ^= 1
array

array([[7, 7, 5],
       [5, 7, 7]])

In [12]:
# Perform left shift with a scalar using <<=
array <<= 1
array

array([[14, 14, 10],
       [10, 14, 14]])