NumPy
- numpy is a python library that provides powerfull and versatile array computaion, mathematical function, and other tool for data analysis and visualization
   

In [1]:
import numpy as np

In [ ]:
# numrical python
# main data structure is an array in numpy

In [2]:
# check version
np.__version__

'1.25.2'

Diffrent ways to create numpy array

In [3]:
x= np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [4]:
# chck for indexing
x[2]

3

In [5]:
x[-1]   # -ve indexing

5

In [6]:
# slicing
x[2:]

array([3, 4, 5])

In [7]:
x[::-1]   # reverse

array([5, 4, 3, 2, 1])

In [8]:
# check dimention
x.ndim

1

In [9]:
# 2D array   2D array array have rows and columns
y = np.array([[10,20],[30,40]])
y

array([[10, 20],
       [30, 40]])

In [10]:
# if we have 2 bracket [[]] that arrya is 2D array

In [11]:
y.ndim   # to check the dimention

2

In [12]:
# array with constant value
#np.full(shape,fill_value)
np.full((3,2),-88)    # 3 rows and 2 col

array([[-88, -88],
       [-88, -88],
       [-88, -88]])

In [13]:
## 1D
np.full(7,100)

array([100, 100, 100, 100, 100, 100, 100])

In [14]:
# 3D array: blocks,rows,col
np.full((4,6,4),-9)

array([[[-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9]],

       [[-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9]],

       [[-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9]],

       [[-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9],
        [-9, -9, -9, -9]]])

In [15]:
# np.ones
np.ones(1)

array([1.])

In [16]:
np.ones(1,)

array([1.])

In [17]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
p = np.zeros(5)
p

array([0., 0., 0., 0., 0.])

In [20]:
p.ndim

1

In [21]:
np.zeros((5,),dtype=int)

array([0, 0, 0, 0, 0])

In [23]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
# array with number sequence
t = np.arange(5)
t

array([0, 1, 2, 3, 4])

In [28]:
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
np.arange(2,21,2)   # start,stop,step


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [35]:
o = np.array([1,2,3,4,5])
o

array([1, 2, 3, 4, 5])

In [31]:
# list
h = [1,2,3,4,5]
h

[1, 2, 3, 4, 5]

In [36]:
o + 100 # # element wise addition,substraction,multiplication we can perform only with array

array([101, 102, 103, 104, 105])

In [39]:
h + [100]

[1, 2, 3, 4, 5, 100]

In [40]:
# numpy is a faster than list

Indexing Over an Array

In [44]:
y = np.array([[1,2,3,4,5],[5,6,7,8,9]])
y

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [45]:
y[0]  # it gives first row

array([1, 2, 3, 4, 5])

In [46]:
# in 2D array indexing works on row

In [49]:
y[::-1]

array([[5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5]])

In [50]:
# work on column
# [row,column]
y[:,:]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [51]:
y[:1]   # get first row

array([[1, 2, 3, 4, 5]])

In [52]:
y[1:]   # get last row

array([[5, 6, 7, 8, 9]])

In [53]:
y[:1,1:]

array([[2, 3, 4, 5]])

In [54]:
y

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [55]:
y[:,1:]

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [56]:
# access 2nd column only
y[:,1]

array([2, 6])

In [57]:
y[:,1:2]  # it gives output in 2D

array([[2],
       [6]])

In [62]:
# modify value 8 to 80
y[:1:3]
y

array([[ 1,  2,  3,  4,  5],
       [80, 80, 80, 80, 80]])

In [63]:
y

array([[ 1,  2,  3,  4,  5],
       [80, 80, 80, 80, 80]])

In [64]:
m = np.array([[1,2,3,4,5],[5,6,7,8,9]])
m

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

In [65]:
m[:1]

array([[1, 2, 3, 4, 5]])

In [66]:
m[1:]

array([[5, 6, 7, 8, 9]])

In [69]:
m[1,3]

8

In [71]:
m[1,3] = 80
m

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7, 80,  9]])

In [72]:
# reverse rows
m[::-1]

array([[ 5,  6,  7, 80,  9],
       [ 1,  2,  3,  4,  5]])

In [73]:
m[:,::-1]    # reverse column

array([[ 5,  4,  3,  2,  1],
       [ 9, 80,  7,  6,  5]])

In [74]:
# reverse both rows and columns
m[::-1,::-1]

array([[ 9, 80,  7,  6,  5],
       [ 5,  4,  3,  2,  1]])

In [75]:
# convert last row into 0
m[1] = 0

In [76]:
m

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0]])

In [77]:
# convert rows to column
# this is called as transpose
m.T

array([[1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0]])

In [78]:
m

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0]])

In [79]:
# one more option using numpy
np.transpose(m)

array([[1, 0],
       [2, 0],
       [3, 0],
       [4, 0],
       [5, 0]])

Check properties of numpy array

In [80]:
m

array([[1, 2, 3, 4, 5],
       [0, 0, 0, 0, 0]])

In [81]:
# check dimention
m.ndim

2

In [83]:
# total number of element
m.size

10

In [84]:
# check rows and columns
m.shape

(2, 5)

In [87]:
# check data type present in the array
m.dtype

dtype('int64')

In [88]:
# we can also create numpy array using random
np.random.random(4)

array([0.94494635, 0.10765474, 0.65717041, 0.95781545])

In [90]:
# 2D
np.random.random([4,4])

array([[0.07269071, 0.66420091, 0.97466232, 0.4880745 ],
       [0.60288903, 0.00525115, 0.69463355, 0.76490676],
       [0.88633632, 0.95490077, 0.45496842, 0.99631878],
       [0.38548465, 0.71705046, 0.64056094, 0.55523935]])

In [91]:
# randint
# (low,high,size)
np.random.randint(2,10,15)

array([9, 7, 8, 3, 5, 5, 5, 6, 3, 8, 6, 4, 7, 8, 7])

In [92]:
np.random.randint(2,10,(5,3))

array([[3, 5, 3],
       [8, 7, 2],
       [3, 6, 9],
       [9, 6, 5],
       [7, 6, 3]])