In [2]:
import numpy as np

In [3]:
# Shape Manipulation of numpy

In [4]:
# 1D
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [5]:

a.shape    # to know size of roes and column


(24,)

In [6]:
# convert to 2D: using reshape
a.reshape(3,8)     # reshape is a temporary

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
# we can use resize to convert array permantly
a.resize(4,6)

In [9]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
# 3D
a.resize(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
a.size

24

In [12]:
a.ndim

3

In [13]:
# n dimension to 1D using ravel()
a.ravel()    # it is temprory

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
# if we want permanant change
a.resize(a.size)

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Mathematical Oerations in numpy

In [16]:
x = np.array([[3,1,5],[0,9,3],[2,12,4]])
x

array([[ 3,  1,  5],
       [ 0,  9,  3],
       [ 2, 12,  4]])

In [17]:
x.ndim

2

In [18]:
# addition od all numbers
x.sum()

39

In [19]:
# row-wise addition
x.sum(axis=1)   # row-wise addition


array([ 9, 12, 18])

In [20]:
# column-wise addition
x.sum(axis=0)

array([ 5, 22, 12])

In [21]:
x.min()

0

In [22]:
x

array([[ 3,  1,  5],
       [ 0,  9,  3],
       [ 2, 12,  4]])

In [24]:
x.max()

12

In [25]:
x.mean()

4.333333333333333

In [26]:
x.std()

3.6514837167011076

In [27]:
x.sin()

AttributeError: 'numpy.ndarray' object has no attribute 'sin'

In [28]:
x.cumsum()

array([ 3,  4,  9,  9, 18, 21, 23, 35, 39])

In [29]:
x.cumprod()

array([ 3,  3, 15,  0,  0,  0,  0,  0,  0])

In [30]:
x

array([[ 3,  1,  5],
       [ 0,  9,  3],
       [ 2, 12,  4]])

In [35]:
# id array is a square array
x.diagonal()

array([3, 9, 4])

In [36]:
x.diagonal?

In [37]:
# fetch the element>=5 # where even >5 is present it return true
x>=5

array([[False, False,  True],
       [False,  True, False],
       [False,  True, False]])

In [38]:
# to fetch actual values: use abbove boolean output a an index
x[x>=5]

array([ 5,  9, 12])

In [39]:
# fetch the even numbers and values > 10
x%2 == 0

array([[False, False, False],
       [ True, False, False],
       [ True,  True,  True]])

In [40]:
(x%2 == 0)
(x>10)

array([[False, False, False],
       [False, False, False],
       [False,  True, False]])